#!/usr/bin/env lua

--[[
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
]]

--- Sum Fibonacci numbers below n.
---@param n number The upper bound for summation.
local function sum_fibs(n)
    local total = 0
    local fibs = {}
    fibs[1] = 1
    fibs[2] = 2
    while fibs[#fibs] < n do
        if fibs[#fibs] % 2 == 0 then
            total = total + fibs[#fibs]
        end
        fibs[#fibs + 1] = fibs[#fibs] + fibs[#fibs - 1]
    end
    return total
end

-- Compute solution
local n = 4000000
print(sum_fibs(n)) -- 4,613,732
